name: Test rust components

on:
  push:
    branches:
      - "**"
    paths:
      - "tests/**"
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --verbose
      - name: run tests
        run: cargo test --verbose
